name: GRACIE
favicon: null
layout_spectrum: 0.99549
typography_spectrum: 0.50451
title: GRACIE CERTIFIED TRAINING CENTER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#2d2d2d'
    - '#a7a7a7'
    - '#6e6e6e'
  brandStrength: 0
  lightness: 0.5355760022066534
  saturation: 0.4781925946008414
  rhythmicContrast: 1
purpose: []
