name: GRACIE
favicon: null
layout_spectrum: 0.99549
typography_spectrum: 0.50451
title: GRACIE CERTIFIED TRAINING CENTER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#ca0000'
    - '#ffffff'
    - '#3b4849'
    - '#808e8e'
  brandStrength: 1
  lightness: 0.5355760022066534
  saturation: 0.4781925946008414
  rhythmicContrast: 0.9312150867190212
purpose: []
